apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: database

patches:
  - target:
      kind: Cluster
      name: tim-db
    patch: |-
      - op: replace
        path: /spec/serviceAccountTemplate/metadata/annotations/azure.workload.identity~1client-id
        value: "PROD_CLIENT_ID_HERE"
      - op: replace
        path: /spec/backup/barmanObjectStore/destinationPath
        value: "https://sttimpro1backup.blob.core.windows.net/backups"
