apiVersion: v1
kind: Secret
metadata:
  name: azure-dns-config
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "012c6d21-cad3-4e61-98dd-2bc660a112b8",
      "subscriptionId": "32dade7a-ad90-464c-a9f3-27221e9f9d73",
      "resourceGroup": "rg-dns",
      "useWorkloadIdentityExtension": true
    }
